# Generated by Django 2.1.7 on 2019-11-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Kullanıcı Adı')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Son Giriş Tarihi')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin mi ?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi ?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Yetkili mi ?')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Super Admin mi ?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
