# Generated by Django 2.1.7 on 2019-11-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.CharField(choices=[('S', 'Satın Alma'), ('M', 'Muhasebe'), ('A', 'ARGE'), ('P', 'Pazarlama'), ('U', 'Üretim'), ('F', 'Finans')], default='D', max_length=1, verbose_name='Departman'),
            preserve_default=False,
        ),
    ]
