# Generated by Django 2.1.7 on 2019-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_last_name',
            field=models.CharField(default='Can Şahin', max_length=60, verbose_name='Ad Soyad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.CharField(choices=[('S', 'Satın Alma'), ('A', 'ARGE'), ('M', 'Muhasebe'), ('F', 'Finans'), ('P', 'Pazarlama'), ('U', 'Üretim')], max_length=1, verbose_name='Departman'),
        ),
    ]
