# Generated by Django 2.1.7 on 2019-11-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20191112_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.CharField(choices=[('S', 'Satın Alma'), ('A', 'ARGE'), ('F', 'Finans'), ('M', 'Muhasebe'), ('U', 'Üretim'), ('P', 'Pazarlama')], max_length=1, verbose_name='Departman'),
        ),
    ]
