# Generated by Django 2.1.7 on 2019-12-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20191112_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.CharField(choices=[('M', 'Muhasebe'), ('P', 'Pazarlama'), ('F', 'Finans'), ('A', 'ARGE'), ('U', 'Üretim'), ('S', 'Satın Alma')], max_length=1, verbose_name='Departman'),
        ),
    ]
