# Generated by Django 2.1.7 on 2019-11-10 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subject', models.CharField(choices=[('U', 'Üretim İş Emri'), ('S', 'Satın Alma'), ('M', 'Müşteri Siparişi'), ('D', 'Diğer')], max_length=1, verbose_name='Konu')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='İçerik')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Onay Bekliyor'), (1, 'Onaylandı'), (2, 'Onaylanmadı')], default=0)),
                ('docnumber', models.CharField(blank=True, max_length=200, verbose_name='Belge No')),
                ('duedate', models.DateField(blank=True, verbose_name='Termin Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
