# Generated by Django 2.1.7 on 2019-11-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='field', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
