# Generated by Django 2.1.7 on 2019-12-10 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mail_group',
            field=models.CharField(choices=[('Y', 'Üst Yönetim'), ('F', 'Finansman'), ('S', 'Satın Alma'), ('M', 'Muhasebe'), ('IP', 'Yurtiçi Satış'), ('IH', 'İhracat Satış'), ('P', 'Üretim Planlama - ARGE')], default='P', max_length=2, verbose_name='Mail Grupları'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Onay Bekliyor'), (1, 'Onaylandı'), (2, 'Reddedildi')], default=0, verbose_name='Mesaj Durumu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('U', 'Üretim İş Emri hk.'), ('P', 'Planlama hk.'), ('S', 'Satın Alma hk.'), ('M', 'Müşteri Siparişi hk.'), ('D', 'Diğer')], max_length=1, verbose_name='Konu'),
        ),
    ]
