# Generated by Django 2.1.7 on 2019-12-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20191210_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Onay Bekliyor'), (1, 'Onaylandı'), (2, 'Reddedildi')], max_length=2, verbose_name='Mesaj Durumu'),
        ),
    ]
