# Generated by Django 2.1.7 on 2019-12-24 07:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20191212_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mail_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Y', 'Üst Yönetim'), ('F', 'Finansman'), ('S', 'Satın Alma'), ('M', 'Muhasebe'), ('IP', 'Yurtiçi Satış'), ('IH', 'İhracat Satış'), ('P', 'Üretim Planlama - ARGE')], max_length=2, null=True, verbose_name='Mail Grupları'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Onay Bekliyor'), ('1', 'Onaylandı'), ('2', 'Reddedildi')], default='0', max_length=2, verbose_name='Mesaj Durumu'),
        ),
    ]
