# Generated by Django 2.1.7 on 2019-12-24 07:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20191224_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mail_group',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Y', 'Üst Yönetim'), ('F', 'Finansman'), ('S', 'Satın Alma'), ('M', 'Muhasebe'), ('IP', 'Yurtiçi Satış'), ('IH', 'İhracat Satış'), ('P', 'Üretim Planlama - ARGE')], max_length=15, null=True, verbose_name='Mail Grupları'),
        ),
    ]
